/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoapp;

import todoapp.controller.ProjectController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
     //  System.out.println(new App().getGreeting());
            
        ProjectController controller = new ProjectController();
        
        
        
        
    }
}
